title: Lê Trung Hoàng
title_enabled: false
name_card:
  name: Lê Trung Hoàng
  office: VNU-HCM University of Science
  position: >
    Faculty of Information Technology <br/>
    Advanced Program in Computer Science
  contacts:
    -
      label: Email
      detail: lthoang@apcs.vn

email: lthoang@apcs.vn
description: >
  Lê Trung Hoàng's personal site
baseurl: ""
url: "lthoang.github.io"
social:
  github: lthoang
  twitter: trhoanglee
  facebook: trhoanglee
  linkedin: lthoang

markdown: kramdown
plugins:
  - jekyll-feed

google_analytics: UA-70844403-1

collections:
  - news