title: Lê Trung Hoàng
title_enabled: false
name_card:
  name: Lê Trung Hoàng
  office: Singapore Management University
  position: >
    PhD Candidate in Data Science and Engineering <br/>
    SMU School of Information Systems
  contacts:
    email: thle.2017 AT smu.edu.sg

contacts:
  office: >
    <br/>SMU School of Information Systems <br/>
    Singapore Management University<br/>
    80 Stamford Road<br/>
    Singapore 178902
  phone: +84-9349-91860 / +65-8424-9685
  email: thle.2017 AT smu.edu.sg
description: >
  Lê Trung Hoàng's personal site
baseurl: ""
url: "lthoang.github.io"
social:
  github: lthoang
  twitter: trhoanglee
  facebook: trhoanglee
  linkedin: in/lthoang

markdown: kramdown
plugins:
  - jekyll-feed

google_analytics: UA-70844403-1

collections:
  - news